//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b.
        /// </summary>
        internal static string bToQuitTesting {
            get {
                return ResourceManager.GetString("bToQuitTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not run selected Task.
        /// </summary>
        internal static string CannotRunSelectedTask {
            get {
                return ResourceManager.GetString("CannotRunSelectedTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose needed lesson from the list above:.
        /// </summary>
        internal static string ChooseNeededLessonFromListAbove {
            get {
                return ResourceManager.GetString("ChooseNeededLessonFromListAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose needed Task ({0}..{1}) from the list above:.
        /// </summary>
        internal static string ChooseNeededTaskFromListAbove {
            get {
                return ResourceManager.GetString("ChooseNeededTaskFromListAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered incorrect value.
        /// </summary>
        internal static string EnteredIncorrectValue {
            get {
                return ResourceManager.GetString("EnteredIncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter only digits inside bounds:.
        /// </summary>
        internal static string EnterOnlyDigitsInsideBounds {
            get {
                return ResourceManager.GetString("EnterOnlyDigitsInsideBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (enter part with numbers).
        /// </summary>
        internal static string enterPartWithNumbers {
            get {
                return ResourceManager.GetString("enterPartWithNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter &quot;q&quot; or &quot;a&quot; or &quot;s&quot;.
        /// </summary>
        internal static string EnterQOrAOrS {
            get {
                return ResourceManager.GetString("EnterQOrAOrS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do, check All Tasks (&quot;a&quot;) or some specific (&quot;s&quot;):.
        /// </summary>
        internal static string HowRunTasks {
            get {
                return ResourceManager.GetString("HowRunTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson.
        /// </summary>
        internal static string Lesson {
            get {
                return ResourceManager.GetString("Lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string LetterAToCheckAllTasks {
            get {
                return ResourceManager.GetString("LetterAToCheckAllTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string LetterSForSpecificTask {
            get {
                return ResourceManager.GetString("LetterSForSpecificTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numbers on left.
        /// </summary>
        internal static string numbersOnLeft {
            get {
                return ResourceManager.GetString("numbersOnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q.
        /// </summary>
        internal static string qToQuitTesting {
            get {
                return ResourceManager.GetString("qToQuitTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you are in the Task, to Quit testing press &quot;q&quot; or &quot;b&quot;..
        /// </summary>
        internal static string WhenYouAreInTheTasktoQuitTestingPressQOrB {
            get {
                return ResourceManager.GetString("WhenYouAreInTheTasktoQuitTestingPressQOrB", resourceCulture);
            }
        }
    }
}
